### ISSUE TITLE
Please consider renaming your starter to swagger2-spring-boot-starter

### ISSUE THREAD

**Issue by wilkinsona** [jianzhichun/spring-boot-starter-swagger2#1]
To make it clear which starters are part of Spring Boot itself and which are developed by the community, we use `spring-boot-starter-foo` for the former and `foo-spring-boot-starter` for the later. Please see [this section of the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming) for more details.

Could you please rename this starter `swagger2-spring-boot-starter` so that it follows these guidelines?

**Comment by jianzhichun** [comment]
Sorry for the inconvenience. Create [issue](https://issues.sonatype.org/browse/OSSRH-29171) in nexus.

**Comment by jianzhichun** [comment]
Done
